name: client-tests

on:
  pull_request:
    branches: ["main"]
    types: ["closed"]

  workflow_dispatch:

jobs:
  test-front:
    runs-on: ubuntu-latest
    steps:
      - name: checkout/code
        uses: actions/checkout@v2
      - name: install
        run: npm i
  docker:
    needs: test-front
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: winterent/winterentfront:latest
